export const STOCKS_LIST_REQUEST = "STOCKS_LIST_REQUEST";
export const STOCKS_LIST_SUCCESS = "STOCKS_LIST_SUCCESS";
export const STOCKS_LIST_FAIL = "STOCKS_LIST_FAIL";

export const STOCKS_CREATE_REQUEST = "STOCKS_CREATE_REQUEST";
export const STOCKS_CREATE_SUCCESS = "STOCKS_CREATE_SUCCESS";
export const STOCKS_CREATE_FAIL = "STOCKS_CREATE_FAIL";

export const STOCKS_DELETE_REQUEST = "STOCKS_DELETE_REQUEST";
export const STOCKS_DELETE_SUCCESS = "STOCKS_DELETE_SUCCESS";
export const STOCKS_DELETE_FAIL = "STOCKS_DELETE_FAIL";

export const STOCKS_UPDATE_REQUEST = "STOCKS_UPDATE_REQUEST";
export const STOCKS_UPDATE_SUCCESS = "STOCKS_UPDATE_SUCCESS";
export const STOCKS_UPDATE_FAIL = "STOCKS_UPDATE_FAIL";
